// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import axios from 'axios'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';
  data = []
  inputValue = ""
  async ngOnInit() { 
    var req = await axios.get("http://localhost:3131")
    this.data = req.data
  }
  async addTodo(){
    await axios.post("http://localhost:3131", {"name":this.inputValue, "completed":false})
    var req = await axios.get("http://localhost:3131")
    this.data = req.data
  }
  async deleteTodo(id){
    await axios.delete("http://localhost:3131/"+id)
    var req = await axios.get("http://localhost:3131")
    this.data = req.data
  }
  async changeStatus(id, co){
    await axios.patch("http://localhost:3131/"+id, {"completed":!co})
    var req = await axios.get("http://localhost:3131")
    this.data = req.data
  }
}

<div style="text-align: center;">
  <div class="todo-item">
    <label >New Todo</label>
    <br />
    <input type="text" [(ngModel)]="inputValue"/>
    <br />
    <br />
    <button (click)="addTodo()" >Add Todo</button>
    <br />
    <br />
  </div>
    <div *ngFor="let todo of data" class="todo-item"> 
      <h3>{{todo.name}}</h3>
      <h6>{{todo.completed == false?"Not Completed":"Completed"}}</h6>
      <button (click)="deleteTodo(todo.id)">Delete Todo</button>
      <button (click)="changeStatus(todo.id, todo.completed)">Change Status</button>
    </div>
</div>

// react-todo/src/App.js
import logo from './logo.svg';
import './App.css';
import { useState, useEffect } from 'react'
import axios from 'axios'

var getTodos = async () => {

  var req = await axios.get("http://localhost:3131")
  return req.data
}


function App() {
  const [inputValue, setInputValue] = useState(null)
  const [data, setdata] = useState([])
  useEffect(async () => {
    var d = await getTodos()
    setdata(d)
  }, []);
  var addTodo = async (name) => {
    console.log(name)
    await axios.post("http://localhost:3131", { "name": name.nativeEvent.data, "completed": false })
    var d = await getTodos()
    setdata(d)
  }

  var deleteTodo = async (id) => {

    var req = await axios.delete("http://localhost:3131/" + id)
    var d = await getTodos()
    setdata(d)

  }
  var changeStatus = async (id, completed) => {

    var req = await axios.patch("http://localhost:3131/" + id, { "completed": !completed })
    var d = await getTodos()
    setdata(d)
  }
  console.log(data);
  return (
    <div className="App">
      <center style={{ marginTop: "150px" }}>
        <div className="todo-item">
          <label htmlFor="">New Todo</label>
          <br />
          <input type="text" onChange={(v) => setInputValue(v)} />
          <br />
          <br />
          <button onClick={() => addTodo(inputValue)}>Add Todo</button>
          <br />
          <br />
        </div>
        {
          data.map((el) => (

            <div className="todo-item" key={el.id}>
              <h3>{el.name}</h3>
              <h6>{el.completed === false ? "Not completed" : "completed"}</h6>
              <button onClick={() => deleteTodo(el.id)}>Delete Todo</button>
              <button onClick={() => changeStatus(el.id, el.completed)}>Change Status</button>
            </div>
          ))
        }
      </center>
    </div>
  );
}

export default App;
